package whenin

import (
	_ "embed"
	"encoding/json"
)

//go:embed index.json
var indexJSON []byte

// AllCandidates parses the embedded city/country index. Mirrors Python
// index.all_candidates (the data is generated by build/build_index.py).
func AllCandidates() ([]Candidate, error) {
	return parseCandidates(indexJSON)
}

func parseCandidates(data []byte) ([]Candidate, error) {
	var cands []Candidate
	if err := json.Unmarshal(data, &cands); err != nil {
		return nil, err
	}
	return cands, nil
}
